module.exports = {
    "Enterprise Cloud Agent": "Cloud Agent",
    "did:prism": "did:prism",
    "PRISM Node": "PRISM Node",
    "PRISM Cloud Agent": "Cloud Agent",
    "Cardano": "Distributed Ledger",
    "atalaprism.io": "https://www.hyperledger.org/projects/identus",
    "PRISM_AGENT_VERSION": "AGENT_VERSION",
    "OPEN_ENTERPRISE_AGENT_VERSION": "AGENT_VERSION",
    "PRISM_NODE_VERSION": "PRISM_NODE_VERSION",
    "PRISM_AGENT_URL": "AGENT_URL",
    "PRISM Mediator": "Mediator",
    "Atala PRISM": "Identus",
    "Atala PRISM platform": "Identus platform",
    "PRISM platform": "Identus platform",
    "PRISM platform v2.0": "Identus platform",
    "io.iohk.atala": "org.hyperledger.identus",
    "io.atala.prism": "org.hyperledger.identus",
    "Atala Mediator": "Mediator",
    "Atala PRISM Mediator": "Mediator",
    "Wallet SDK TS": "Edge Agent SDK TS",
    "Wallet SDK KMM": "Edge Agent SDK KMP",
    "Wallet SDK Swift": "Edge Agent SDK Swift",
    // "Apollo": "Apollo",
    // "[Logos]": "[Remove]",
    // "Agent": "[Update]",
    // "[Unresolvable reference]": "[use a placeholder]",
    "atala-prism-building-blocks": "identus-cloud-agent",
    "https://github.com/hyperledger-labs/open-enterprise-agent": "https://github.com/hyperledger/identus-cloud-agent",
    "https://github.com/input-output-hk/atala-prism-mediator": "https://github.com/input-output-hk/identus-mediator",
    "https://github.com/input-output-hk/atala-prism-wallet-sdk-ts": "https://github.com/input-output-hk/identus-edge-agent-sdk-ts",
    "https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm": "https://github.com/input-output-hk/identus-edge-agent-sdk-kmp",
    "https://github.com/input-output-hk/atala-prism-wallet-sdk-swift": "https://github.com/input-output-hk/identus-edge-agent-sdk-swift",
    "https://github.com/input-output-hk/atala-prism-apollo/": "https://github.com/input-output-hk/identus-apollo/",
    "https://github.com/input-output-hk/atala-prism-didcomm-kmm": "N/A",
    "https://github.com/input-output-hk/atala-prism-didcomm-swift": "N/A",
    "https://github.com/input-output-hk/anoncred-kmm/": "N/A",
    "https://github.com/input-output-hk/atala-prism-docs": "https://github.com/input-output-hk/identus-docs",
    "https://github.com/input-output-hk/atala-releases": "N/A",
    "atala-coredid@iohk.io": "No change for now",
    "atala@iohk.io": "No change for now",
    "atalaprism@iohk.io": "No change for now",
    "IOHK": "Hyperledger (see note --> )",
    "https://sit-prism-mediator.atalaprism.io//": "N/A",
    "https://sandbox-mediator.atalaprism.io/": "N/A",
    // "https://didcomm.atalaprism.io/present-proof/3.0/request-presentation": "N/A (this would cause a breaking change)",
    "https://coveralls.io/github/input-output-hk/atala-prism-wallet-sdk-ts": "TBC",
    "ATALA_GITHUB_TOKEN": "GITHUB_TOKEN (and update references to the variable)",
    "https://coveralls.io/github/input-output-hk/atala-prism-building-blocks?branch=main": "https://coveralls.io/github/hyperledger/identus-cloud-agent?branch=main",
    "https://coveralls.io/repos/github/input-output-hk/atala-prism-building-blocks/badge.svg": "https://coveralls.io/repos/github/hyperledger/identus-cloud-agent/badge.svg?branch=main",
    "https://docs.atalaprism.io": "N/A (see comment)",
    "PRISM Schema registry": "Schema registry",
    "OEA": "ICA",
    "OEA team": "Identus maintainers",
    "OEA ecosystem": "Identus ecosystem",
}